### ISSUE TITLE
有问题,RJVideoPlayer可不可以别强制引用这个库?

### ISSUE THREAD

**Issue by shenguanjiejie** [changsanjiang/SJFullscreenPopGesture#1]
![image](https://user-images.githubusercontent.com/9425605/38549735-578c3ff6-3ce7-11e8-9ac9-0d3b5decbf19.png)
有时候会有push到下一个navigationController的需求,这样做太粗暴了.

**Comment by changsanjiang** [comment]
'Pushing a navigation controller is not supported'.. 系统是不支持的...

**Comment by changsanjiang** [comment]
![wechatimg1043](https://user-images.githubusercontent.com/25744224/38551055-cb169f5e-3cea-11e8-8968-56e8e56a6dba.jpeg)
.... 这种操作 系统是不支持的, 如果要push 下一个界面都是UIViewController

**Comment by shenguanjiejie** [comment]
好吧 是我记错了 抱歉~😅
