### ISSUE TITLE
swift编译错误，1.4.8版本

### ISSUE THREAD

**Issue by namo-py** [changsanjiang/SJFullscreenPopGesture#10]
else if ( self.children.count <= 1 ) {
            return false
        }
        else if ( self.children.last?.isKind(of: UINavigationController.self) )! {
            return false
        }
编译报错！389行，是不是不支持？

**Comment by changsanjiang** [comment]
是直接拖进去的吗?   1.4.8 使用的是swift4.2版本的

**Comment by changsanjiang** [comment]
可以用 1.4.7 版本的,  那个是swift4.0版本的
