### ISSUE TITLE
是不是不支持swift4.1？

### ISSUE THREAD

**Issue by namo-py** [changsanjiang/SJFullscreenPopGesture#2]
你好，我在swift4.1使用了全屏返回，一般的界面全屏返回没有问题，但在有视频播放的界面滑动返回就crash了，已经设置了fade_views

报错在方法：
private func SJ_cancellGesture(_ gesture: UIGestureRecognizer) -> Void {
        gesture.setValue(UIGestureRecognizerState.cancelled, forKey: "state")
    }
输出：
[_SwiftValue longLongValue]: unrecognized selector sent to instance 0x1c0444d70

**Comment by changsanjiang** [comment]
ok, 我测试一下

**Comment by changsanjiang** [comment]
你好, 先改成这个吧. 
```swift
gesture.setValue(UIGestureRecognizerState.cancelled.rawValue, forKey: "state")
```

**Comment by namo-py** [comment]
Pod升一个版本可以么，也就几分钟的事情，这样我就不用修改Pod库了




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            胡家驹
                            
                            
                                
                                    邮箱：nanhujiaju@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年05月07日 17:23，changsanjiang 写道： 你好, 先改成这个吧. gesture.setValue(Int8(UIGestureRecognizerState.cancelled.rawValue), forKey: "state")

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changsanjiang/SJFullscreenPopGesture","title":"changsanjiang/SJFullscreenPopGesture","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/changsanjiang/SJFullscreenPopGesture"}},"updates":{"snippets":[{"icon":"PERSON","message":"@changsanjiang in #2: 你好, 先改成这个吧. gesture.setValue(Int8(UIGestureRecognizerState.cancelled.rawValue), forKey: \"state\")\r\n"}],"action":{"name":"View Issue","url":"https://github.com/changsanjiang/SJFullscreenPopGesture/issues/2#issuecomment-387009535"}}}

**Comment by changsanjiang** [comment]
行

**Comment by namo-py** [comment]
你好，我看到你把objc的Pod库更新到1.4.1了，swift版本还没有更新是吧




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            胡家驹
                            
                            
                                
                                    邮箱：nanhujiaju@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年05月07日 20:20，changsanjiang 写道： Closed #2 via ea18501.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changsanjiang/SJFullscreenPopGesture","title":"changsanjiang/SJFullscreenPopGesture","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/changsanjiang/SJFullscreenPopGesture"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #2 via ea1850168040ef1d643f8c091e9b49bfb3a9cef0."}],"action":{"name":"View Issue","url":"https://github.com/changsanjiang/SJFullscreenPopGesture/issues/2#event-1612794666"}}}

**Comment by changsanjiang** [comment]
是的, 我正在推到主杆上, 网速比较慢
swift 版本的和OC的同步了一下

**Comment by changsanjiang** [comment]
@hujiaju 你好兄弟, swift的也更新好了

**Comment by namo-py** [comment]
OK，我更新一下




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            胡家驹
                            
                            
                                
                                    邮箱：nanhujiaju@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年05月07日 20:47，changsanjiang 写道： @hujiaju 你好兄弟, swift的也更新好了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changsanjiang/SJFullscreenPopGesture","title":"changsanjiang/SJFullscreenPopGesture","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/changsanjiang/SJFullscreenPopGesture"}},"updates":{"snippets":[{"icon":"PERSON","message":"@changsanjiang in #2: @hujiaju 你好兄弟, swift的也更新好了"}],"action":{"name":"View Issue","url":"https://github.com/changsanjiang/SJFullscreenPopGesture/issues/2#issuecomment-387053429"}}}
