### ISSUE TITLE
shadeAndShifting 怪怪的

### ISSUE THREAD

**Issue by CivelXu** [changsanjiang/SJFullscreenPopGesture#3]
是bug吗
![img_1605](https://user-images.githubusercontent.com/19768199/40887748-b9591de0-677f-11e8-8cdf-1e8c9b82c7f5.PNG)

**Comment by CivelXu** [comment]
另外还有一个问题, 第一个 vc 的tableview cell点击 背景颜色 会在 手势返回的过程 中 看到 点击背景颜色;
应该是 push 之前 截图了?  

在点击 push 第二个vc 之前 我已经重置了
`        
tableView.deselectRow(at: indexPath, animated: true)
`
现在 pop 可以看到 cell 背景 从 灰色 变 没有 很奇怪

**Comment by changsanjiang** [comment]
第一个问题是不是项目之前存在全屏手势?    第二个显示问题, 可以设置一下[显示模式](https://github.com/changsanjiang/SJFullscreenPopGesture/blob/7678a2ffcbde38fd031071a35a3a7fd6b51a1d97/SJFullscreenPopGesture/UIViewController%2BSJVideoPlayerAdd.h#L27)

**Comment by CivelXu** [comment]
第一个问题: 项目之前存在全屏手势 已经被我删除了 
第二个问题: 我已经设置了 self.sj_displayMode = .origin 还是一样; 我是在Base Nav 里面设置的

**Comment by changsanjiang** [comment]
第一个问题, 我查一查代码
第二个问题, 额.. 显示模式是每个vc的, 不是nav的. 所以没起作用.  我建议使用截屏方式返回(截屏是默认的), 必要的地方再使用原始视图

**Comment by CivelXu** [comment]
使用原始视图, 你这边调整edgesForExtendedLayout 会有布局的bug, 采用截图方式 有没有办法延迟 一点 ..

**Comment by changsanjiang** [comment]
对了, pod库用的是最新版本的吗?

**Comment by changsanjiang** [comment]
是 1.4.1 吗

**Comment by CivelXu** [comment]
用的是  1.4.1 我刚使用的
