### ISSUE TITLE
能不能解决mapView的手势冲突问题？

### ISSUE THREAD

**Issue by HZRZCW** [changsanjiang/SJFullscreenPopGesture#5]
就是在地图页面也可以侧滑返回。

**Comment by changsanjiang** [comment]
好的, 我晚上测试一下

**Comment by changsanjiang** [comment]
Hello, @HZRZCW 最新版本的我处理了一下, `pod update` 一下看看.

**Comment by HZRZCW** [comment]
首先感谢你的回复和更新，我直接用你的最新demo测试了一下，还是发现了一些问题：
1、地图界面在加上self.sj_fadeArea = @[[NSValue valueWithCGRect:(CGRect){CGPointMake(10, 0), self.view.frame.size}]]; 这句代码的情况下，SJFullscreenPopGestureType_EdgeLeft模式下可以左侧滑返回，但是侧滑响应距离超过10，调整为5也是一样； SJFullscreenPopGestureType_Full模式下可以全屏返回。
2、地图界面在注释掉self.sj_fadeArea = @[[NSValue valueWithCGRect:(CGRect){CGPointMake(10, 0), self.view.frame.size}]]; 这句代码的情况下，和以上情况一样。
3、在地图界面某些时候会出现SJFullscreenPopGestureType_Full模式下完全不能侧滑返回的情况，极少见，很难复现。
4、如果没有在地图界面测试，pageVC的第n+1界面可以滑动回第n界面，第一个界面也可以侧滑返回，但是如果在地图界面测试后回到pageVC界面的话，pageVC的第n+1界面不可以滑动回第n界面，而是直接返回上一个控制器了。

**Comment by changsanjiang** [comment]
设置了盲区, 是在full手势的情况下, 才会考虑的, 而edge手势, 不考虑盲区. 

pageVC的问题 , 我调整一下.  

更新的太急, 没好好测试,  见谅..

**Comment by HZRZCW** [comment]
又试了下，在地图界面SJFullscreenPopGestureType_Full模式下设置self.sj_fadeArea = @[[NSValue valueWithCGRect:(CGRect){CGPointMake(10, 0), self.view.frame.size}]];不起作用，不能侧滑返回。等你更新。

**Comment by changsanjiang** [comment]
建议设置成`>=30`; 10个点不好判断 😓

**Comment by changsanjiang** [comment]
@HZRZCW pageVC已修复.

edge手势不支持盲区, 因为它在屏幕边缘触发, 所以忽略了盲区.

**Comment by HZRZCW** [comment]
完美，非常感谢！
