### ISSUE TITLE
sj_displayMode 感觉失效了，改了也没变化。

### ISSUE THREAD

**Issue by HZRZCW** [changsanjiang/SJFullscreenPopGesture#6]
经过测试sj_displayMode属性失效了，怎么改都是SJPreViewDisplayMode_Origin模式。

**Comment by changsanjiang** [comment]
恩,  我去测试一下

**Comment by changsanjiang** [comment]
@HZRZCW 我这边测试正常...

**Comment by changsanjiang** [comment]
默认是这个模式(`_Snapshot`), 怎么会是`_Origin`呢?  是不是版本太旧了? 奇怪..
