### ISSUE TITLE
sj_displayMode 属性失效问题

### ISSUE THREAD

**Issue by HZRZCW** [changsanjiang/SJFullscreenPopGesture#7]
我把你的最新demo手动导入我的项目中，然后在BaseVC和BaseNavigaiton中无论设置了self.sj_displayMode = SJPreViewDisplayMode_Origin; 还是 self.sj_displayMode = SJPreViewDisplayMode_Snapshot; 效果都是如gif图所示那样，很奇怪。

![gif](https://user-images.githubusercontent.com/12219811/43115889-e3eb188a-8f37-11e8-854e-60c1ef981d89.gif)

**Comment by changsanjiang** [comment]
是不是不想要那个 灰色的遮罩?

**Comment by changsanjiang** [comment]
设置一下 NavigationController的扩展属性:
```Objective-C
    self.sj_transitionMode = SJScreenshotTransitionModeShifting;
```

**Comment by HZRZCW** [comment]
对，不想要，SJPreViewDisplayMode_Origin不是没有遮罩效果的意思？

**Comment by changsanjiang** [comment]
汗,  不是那个意思. 如果才用的是 Origin, 那么返回时, 你可以注意到底部的页面Gif还是在动的.  而如果采用截屏, 底部页面的GIF不会动.

**Comment by changsanjiang** [comment]
看来名字没起好 😓

**Comment by changsanjiang** [comment]
推荐使用截屏的方式,  必要的情况下再使用 Origin

**Comment by HZRZCW** [comment]
我理解错了，最好加上更详细一点的中文说明吧，谢谢。

**Comment by changsanjiang** [comment]
恩, 下一步更新的时候, 我会加上的
