### ISSUE TITLE
能不能在这个框架里面加上可以隐藏导航栏的方法或属性

### ISSUE THREAD

**Issue by HZRZCW** [changsanjiang/SJFullscreenPopGesture#8]
就像FDFullscreenPopGesture那样，可以在某个控制器中隐藏导航栏而不影响其他页面。

**Comment by changsanjiang** [comment]
额, 加上这个功能, 需要交换系统的两个方法(WillAppear, WillDisappear).. 交换会增加莫名其妙的问题, 还是不加的好. 

我一致是这样隐藏的
```Objective-C
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.navigationController setNavigationBarHidden:NO animated:YES];
}
```

**Comment by HZRZCW** [comment]
我试过这样- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.navigationController setNavigationBarHidden:NO animated:YES];
}隐藏，但是在tabBarController切换tabitem时出现问题了，

![gif](https://user-images.githubusercontent.com/12219811/43121047-039e0950-8f4f-11e8-9611-a08fb0d598a6.gif)
有可能是我用了https://github.com/MoZhouqi/KMNavigationBarTransition这个管理导航栏样式的框架导致的。

**Comment by changsanjiang** [comment]
试一下不做动画看看

**Comment by HZRZCW** [comment]
不做动画就没问题了，感谢。

**Comment by HZRZCW** [comment]
大神你这么厉害，可以写一个类似https://github.com/MoZhouqi/KMNavigationBarTransition这个框架用来管理导航栏样式的框架嘛，实现像微信那样平滑切换不同导航栏样式的控制器。

**Comment by changsanjiang** [comment]
汗... 以后吧, 看看能不能集成到这个手势库里.

**Comment by changsanjiang** [comment]
@HZRZCW 兄弟, 你更新一下库吧, 我完善了一下 处理其他pan手势的情况
